name: food_ordering_app
description: "A new Flutter project."

publish_to:


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.6
  flutter_screenutil: ^5.9.1
  http: ^1.2.1
  font_awesome_flutter: ^10.4.0
  flutter_staggered_animations: ^1.1.1
  motion_tab_bar: ^2.0.4
  searchfield: ^1.0.3
  avatar_glow: ^3.0.1
  firebase_database: ^10.5.6
  cloud_firestore: ^4.17.5
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  image_gradient: ^0.0.2
  gap: ^3.0.1
  item_count_number_button: ^1.9.2
  provider: ^6.1.2




  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
